version: "3"

services:
  app:
    build:
      context: .
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s
    command: node index.js
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:5.7.12
    container_name: db
    command: --innodb-use-native-aio=0
    tty: true
    restart: always
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      -  app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
